### ISSUE TITLE
Use code in eclipse project

### ISSUE THREAD

**Issue by patriciastar** [chili-epfl/attention-tracker#7]
Hi everyone,
I use Ubuntu 64-bit (in a VM: VirtualBox) and downloaded and installed your code (attention-tracker) as explained in the README and the code sample "head_pose_test" runs fine from console.
My question is: I would like to use this code in an eclipse project (to combine with other code, easy debugging and so on).
I'm a beginner on this field and so I tried many things but can not include it correctly.
In detail: I created a new project, copied the files into src directory, set up for dlib, opencv and ros (in properties).
I have the problem in class "estimated_focus.cpp": Type ' std_msgs::ColorRGBA ' could not be resolved. Google did not help me with this, yet.

Can anyone help me with this please?
Thanks a lot.
Patricia

**Comment by WafaJohal** [comment]
Hello, 
It is probably due to some settings for the CMake that should be done in eclipse to locate the ROS packages. 
I use the catkin environment of ROS.  
Here is what I found about setting up catkin in eclipse
https://github.com/ethz-asl/programming_guidelines/wiki/Catkin-Eclipse
Hope it'll help, 

Wafa
